# InteractiveLab (原 GenartLib) Packaging Clean Script (auto-generated by Packaging Manager)
# 用法: 打包完成后运行此脚本，清理打包目录中排除模块的 DLL/模型文件，并拷贝许可证
#   PowerShell.exe -ExecutionPolicy Bypass -File CleanPackaging.ps1 -PackageDir "<打包输出目录>"

param(
    [Parameter(Mandatory=$true)]
    [string]$PackageDir
)

$ErrorActionPreference = 'Stop'
Write-Host "=== InteractiveLab Packaging Clean ===" -ForegroundColor Cyan
Write-Host "Package dir: $PackageDir"

# 找到打包目录里的插件目录（位于 <Game>/Plugins/ 或 Engine/Plugins/Marketplace/ 等）。
# 插件已由 genartlib 更名为 InteractiveLab，两个名字都尝试匹配。
$PluginDirs = @()
foreach ($name in @('InteractiveLab', 'genartlib')) {
    $PluginDirs += Get-ChildItem -Path $PackageDir -Recurse -Directory -Filter $name -ErrorAction SilentlyContinue
}
$GenartPluginDir = $PluginDirs | Select-Object -First 1
if (-not $GenartPluginDir) {
    Write-Host "[!] InteractiveLab plugin directory not found in package, skipping." -ForegroundColor Yellow
} else {
    $PluginRoot = $GenartPluginDir.FullName
    Write-Host "Found InteractiveLab at: $PluginRoot"

    Write-Host "(no modules to exclude)"
}

# === License Auto-Copy ===
# 从项目编辑器的 Config/GenartLicense.json 拷贝到打包结果的 Config/ 目录
$ProjectConfig = 'E:/P4worksSpace2/LG_Main/lingangInstallation/Config/'
$SrcLicense = Join-Path $ProjectConfig 'GenartLicense.json'
if (Test-Path $SrcLicense) {
    # 找到打包目录里的游戏 Config 目录（通常在 <Game>/Config，与 genartlib 同级或更深一级）
    $GameConfigDir = Get-ChildItem -Path $PackageDir -Recurse -Directory -Filter 'Config' -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch 'Engine' -and $_.FullName -notmatch 'Plugins' } | Select-Object -First 1
    if ($GameConfigDir) {
        $DstLicense = Join-Path $GameConfigDir.FullName 'GenartLicense.json'
        Copy-Item $SrcLicense $DstLicense -Force
        Write-Host "[v] Copied license: $SrcLicense -> $DstLicense" -ForegroundColor Green
    } else {
        Write-Host "[!] Game Config dir not found in package, cannot copy license." -ForegroundColor Yellow
    }
} else {
    Write-Host "[!] No license file at $SrcLicense" -ForegroundColor Yellow
    Write-Host "    GenartLib will run in trial/restricted mode." -ForegroundColor Yellow
}

Write-Host "=== Done ===" -ForegroundColor Cyan
